futuretech/futuretech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
	path('admin/', admin.site.urls),
  path('', include('posts.urls')),
	path('', include('userauth.urls')),
	path('', include('sales.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

futuretech/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.listPosts, name='home'),
]

urlpatterns += [
  path('product/<int:post_id>/', views.productPage, name='productPage'), 
]

urlpatterns += [
	path('sellerprofile/sellercentral/createpost/', views.createPost, name='createPost'),
  path('sellerprofile/sellercentral/modifypost/<int:post_id>/', views.modifyPost, name='modifyPost'),
]

urlpatterns += [
  path('product/<int:post_id>/buynow', views.buyNow, name='buyNow')
]

futuretech/posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
  name = models.CharField(max_length=200)

  def __str__(self):
    return self.name

class Brand(models.Model):
  name = models.CharField(max_length=200)

  def __str__(self):
    return self.name

class Seller(models.Model):
  userId = models.OneToOneField(User, on_delete=models.CASCADE)
  publicName = models.CharField(max_length=200)

  def __str__(self):
    return self.publicName
  
class Post(models.Model):
  class Condition(models.TextChoices):
    NEW = "New"
    USED = "Used"
    REFURBISHED = "Refurbished"

  title = models.CharField(max_length=200)
  description = models.CharField(max_length=200)
  condition = models.CharField(choices=Condition.choices, max_length=100)
  categoryId = models.ForeignKey(Category, on_delete=models.CASCADE)
  originalPrice = models.DecimalField(max_digits=8, decimal_places=2)
  brandId = models.ForeignKey(Brand, on_delete=models.CASCADE)
  stock = models.IntegerField(default=0)
  sellerId = models.ForeignKey(Seller, on_delete=models.CASCADE)

  def __str__(self):
    return self.title
  
  def getCategoryName(self):
    return self.categoryId.name
  
  def getBrandName(self):
    return self.brandId.name

class PostImage(models.Model):
  postId = models.ForeignKey(Post, on_delete=models.CASCADE)
  image = models.ImageField(upload_to='images/', default='images/logo.png')

  def __str__(self):
    return self.postId.title

futuretech/posts/forms.py
from django import forms
from .models import Post, PostImage

class PostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ['title', 'description', 'condition', 'categoryId', 'originalPrice', 'brandId', 'stock']
    labels = {
      'title': 'Title',
      'description': 'Description',
      'condition': 'Condition',
      'categoryId': 'Category',
      'originalPrice': 'Original Price',
      'brandId': 'Brand',
      'stock': 'Stock',
    }
    widgets = {
      'title': forms.TextInput(attrs={'class': 'form-control'}),
      'description': forms.TextInput(attrs={'class': 'form-control'}),
      'condition': forms.Select(attrs={'class': 'form-control'}),
      'categoryId': forms.Select(attrs={'class': 'form-control'}),
      'originalPrice': forms.NumberInput(attrs={'class': 'form-control'}),
      'brandId': forms.Select(attrs={'class': 'form-control'}),
      'stock': forms.NumberInput(attrs={'class': 'form-control'}),
    }

class PostImageForm(forms.ModelForm):
  class Meta:
    model = PostImage
    fields = ['postId','image']
    exclude = ['postId']
    image = forms.ImageField(help_text='Upload an image', widget=forms.FileInput(attrs={'class': 'form-control'}))

class QuantityForm(forms.Form):
  quantity = forms.IntegerField(label='quantity' ,min_value=1, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    

futuretech/posts/views.py
from email.mime import image
from django.http import HttpRequest
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import PostForm, PostImageForm, QuantityForm
from .models import Post, Seller, Category
from sales.models import ProductSold, Sale

def navBar(request):
  user = request.user
  is_seller = Seller.objects.filter(userId=user).exists()
  return render(request, 'navbar.html', {'user': user}, {'seller': is_seller})

def listPosts(request):
  phones = Category.objects.get(name='Phones')
  headphones = Category.objects.get(name='Headphones')
  laptops = Category.objects.get(name='Laptops')
  gameConsoles = Category.objects.get(name='Game Consoles')
  peripherals = Category.objects.get(name='Peripherals')

  PhonesPosts = Post.objects.filter(categoryId=phones)
  HeadphonesPosts = Post.objects.filter(categoryId=headphones)
  LaptopsPosts = Post.objects.filter(categoryId=laptops)
  GameConsolesPosts = Post.objects.filter(categoryId=gameConsoles)
  PeripheralsPosts = Post.objects.filter(categoryId=peripherals)
  
  AllPosts = Post.objects.all()
  context = {
    'posts': AllPosts,
    'phones': PhonesPosts,
    'headphones': HeadphonesPosts,
    'laptops': LaptopsPosts,
    'gameConsoles': GameConsolesPosts,
    'peripherals': PeripheralsPosts,
  }
  return render(request, 'index.html', context)

def productPage(request, post_id):
  post = get_object_or_404(Post, pk=post_id)
  form = QuantityForm()
  return render(request, 'productPage.html', {'post': post, 'form': form})
  
@login_required
def modifyPost(request, post_id):
  if request.method == 'GET':
    try:
      seller = Seller.objects.get(userId=request.user)
      post = get_object_or_404(Post, pk=post_id, sellerId=seller)
      form = PostForm(instance=post)
    except ValueError:
      return redirect('sellerCentral')
    return render(request, 'modifyPost.html', {'post': post, 'form': form})
  else:
    try:
      seller = Seller.objects.get(userId=request.user)
      post = get_object_or_404(Post, pk=post_id, sellerId=seller)
      form = PostForm(instance=post)
      form.save()
      return redirect('sellerCentral')
    except ValueError:
      return render(request, 'modifyPost.html', {'post': post, 'form': form, 'error': 'Bad data passed in. Try again.'})

@login_required
def createPost(request):
    if request.method == 'GET':
        return render(request, 'createPost.html', {'form': PostForm, 'imageForm': PostImageForm})
    else:
        imageForm = PostImageForm(request.POST, request.FILES)
        form = PostForm(request.POST)
        if form.is_valid():
            seller = Seller.objects.get(userId=request.user)
            new_post = form.save(commit=False)
            new_post.sellerId = seller
            new_post.save()
            image = imageForm.save(commit=False)
            image.postId = new_post
            image.save()
            return redirect('sellerCentral')
        else:
            return render(request, 'createPost.html', {'form': form, 'imageForm': imageForm, 'error': 'Bad data passed in. Try again.'})
        
@login_required
def buyNow(request, post_id):
  if request.method == 'GET':
    post = get_object_or_404(Post, pk=post_id)
    form = QuantityForm()
    return render(request, 'productPage.html', {'post': post, 'form': form})
  else:
    form = QuantityForm(request.POST)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
      quantity = form.cleaned_data['quantity']
      sale = Sale.objects.create(userId=request.user)
      ProductSold.objects.create(postId=post, saleId=sale, pricePerunit=post.originalPrice, amount=quantity)
      post.stock -= quantity
      return redirect('home')
    else:
      return render(request, 'productPage.html', {'post': post, 'form': form, 'error': 'Bad data passed in. Try again.'})

futuretech/posts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
</head>
<body>
  {% block content %}
  {% endblock %}
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</html>

futuretech/posts/templates/createPost.html
{% extends "base.html" %} {% block content %} 
{% load static %} 
{% include 'navbar.html' %}

<title>Create post</title>
<div class="container mt-4">
  <h2>Create post</h2>
  <div>
    <form action="{% url 'createPost' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-body">
              <h5 class="card-text">Name of the Post</h5>
              <h4 class="card-title">{{form.title}}</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <div class="card-body">
              <label for="">Condition</label>
              {{form.condition}}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div class="card h-75">
            <div class="card-body">
              <h5 class="card-title">Description of the Post</h5>
              <p class="card-text">{{form.description}}</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <div class="card-body">
              <div class="form-group">
                <label for="category">Category</label>
                {{ form.categoryId }}
              </div>
              <div class="form-group">
                <label for="brand">Brand</label>
                {{ form.brandId }}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-text">Images</h5>
              <div class="d-flex flex-wrap">
                <img
                src="https://via.placeholder.com/150"
                class="img-thumbnail m-2"
                alt="Image 1"
                />
                <img
                src="https://via.placeholder.com/150"
                class="img-thumbnail m-2"
                alt="Image 2"
                />
                <img
                src="https://via.placeholder.com/150"
                class="img-thumbnail m-2"
                alt="Image 3"
                />
              </div>
              {{imageForm}}
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card h-100">
            <div class="card-body">
              <div class="form-group">
                <label for="">Stock</label>
                {{ form.stock}}
              </div>
            <div class="form-group">
              <label for="">Original price</label>
              {{ form.originalPrice}}
            </div>
          </div>
        </div>
      </div>
      </div>
      {{error}}
      <button type="submit" class="btn btn-primary" style="margin-top: 15px;">Create</button>
    </form>
  </div>
</div>
{% endblock %}

futuretech/posts/templates/footer.html
{% extends 'base.html'%} {% block content %}
{% load static %}
<footer class="bg-dark text-light text-center py-3">
    <p>&copy; 2023 Future Tech. Todos los derechos reservados.</p>
</footer>
{% endblock %}
  

futuretech/posts/templates/index.html
{% extends 'base.html'%} {% block content %} 
{% load static %} 
{% include 'navbar.html' %}
<title>FutureTech</title>
<section class="section-products">
  <div class="container">
    <!-- Phones -->
    <div class="row justify-content-center text-center section-title">
      <div class="col-md-8 col-lg-6">
        <div class="header">
          <h2><strong>Phones 📱</strong></h2>
        </div>
      </div>
    </div>

    <div class="row justify-content-center text-center">
      {% for phone in phones %}
      <div class="col-md-3">
        <div class="card" style="width: 100%">
          {% for post_image in phone.postimage_set.all %}
          <a href="{% url 'productPage' phone.id %}">
            <img
              src="{{ post_image.image.url }}"
              class="card-img-top zoom-img"
              alt="{{phone.title}}"
            />
          </a>
          {% endfor %}
          <div class="card-body">
            <h6 class="card-title"><strong>{{ phone.title }}</strong></h6>
            <p class="card-text">Price: ${{ phone.originalPrice }}</p>
            <p class="card-text">Stock: {{ phone.stock }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <!-- Headphones -->
    <div class="row justify-content-center text-center section-title">
      <div class="col-md-8 col-lg-6">
        <div class="header">
          <h2><strong>Headphones 🎧</strong></h2>
        </div>
      </div>
    </div>

    <div class="row justify-content-center text-center">
      {% for headphone in headphones %}
      <div class="col-md-3">
        <div class="card" style="width: 100%">
          {% for post_image in headphone.postimage_set.all %}
          <a href="{% url 'productPage' headphone.id %}">
            <img
              src="{{ post_image.image.url }}"
              class="card-img-top zoom-img"
              alt="{{headphone.title}}"
            />
          </a>
          {% endfor %}
          <div class="card-body">
            <h6 class="card-title"><strong>{{ headphone.title }}</strong></h6>
            <p class="card-text">Price: ${{ headphone.originalPrice }}</p>
            <p class="card-text">Stock: {{ headphone.stock }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <!-- Game Console -->
    <div class="row justify-content-center text-center section-title">
      <div class="col-md-8 col-lg-6">
        <div class="header">
          <h2><strong>Game Console 🎮</strong></h2>
        </div>
      </div>
    </div>

    <div class="row justify-content-center text-center">
      {% for gameConsole in gameConsoles %}
      <div class="col-md-3">
        <div class="card" style="width: 100%">
          {% for post_image in gameConsole.postimage_set.all %}
          <a href="{% url 'productPage' gameConsole.id %}">
            <img
              src="{{ post_image.image.url }}"
              class="card-img-top zoom-img"
              alt="{{gameConsole.title}}"
            />
          </a>
          {% endfor %}
          <div class="card-body">
            <h6 class="card-title"><strong>{{ gameConsole.title }}</strong></h6>
            <p class="card-text">Price: ${{ gameConsole.originalPrice }}</p>
            <p class="card-text">Stock: {{ gameConsole.stock }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <!-- Laptops -->
    <div class="row justify-content-center text-center section-title">
      <div class="col-md-8 col-lg-6">
        <div class="header">
          <h2><strong>Laptops 💻</strong></h2>
        </div>
      </div>
    </div>

    <div class="row justify-content-center text-center">
      {% for laptop in laptops %}
      <div class="col-md-3">
        <div class="card" style="width: 100%">
          {% for post_image in laptop.postimage_set.all %}
          <a href="{% url 'productPage' laptop.id %}">
            <img
              src="{{ post_image.image.url }}"
              class="card-img-top zoom-img"
              alt="{{laptop.title}}"
            />
          </a>
          {% endfor %}
          <div class="card-body">
            <h6 class="card-title"><strong>{{ laptop.title }}</strong></h6>
            <p class="card-text">Precio: ${{ laptop.originalPrice }}</p>
            <p class="card-text">Stock: {{ laptop.stock }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <!-- Peripherals -->
    <div class="row justify-content-center text-center section-title">
      <div class="col-md-8 col-lg-6">
        <div class="header">
          <h2><strong>Peripherals 🖱</strong></h2>
        </div>
      </div>
    </div>

    <div class="row justify-content-center text-center">
      {% for peripherals in peripherals %}
      <div class="col-md-3">
        <div class="card" style="width: 100%">
          {% for post_image in peripherals.postimage_set.all %}
          <a href="{% url 'productPage' peripherals.id %}">
            <img
              src="{{ post_image.image.url }}"
              class="card-img-top zoom-img"
              alt="{{peripherals.title}}"
            />
          </a>
          {% endfor %}
          <div class="card-body">
            <h6 class="card-title"><strong>{{ peripherals.title }}</strong></h6>
            <p class="card-text">Precio: ${{ peripherals.originalPrice }}</p>
            <p class="card-text">Stock: {{ peripherals.stock }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="row justify-content-center text-center">
      <div class="col-md-8 col-lg-6">
        <div class="header">
          <h2><strong>All Products 🔥</strong></h2>
        </div>
      </div>
    </div>

    <div class="container mt-5">
      <div class="row justify-content-center text-center">
        {% for post in posts %}
        <div class="col-md-3">
          <div class="card" style="width: 100%">
            {% for post_image in post.postimage_set.all %}
            <a href="{% url 'productPage' post.id %}">
              <img
                src="{{ post_image.image.url }}"
                class="card-img-top zoom-img"
                alt="{{post.title}}"
              />
            </a>
            {% endfor %}
            <div class="card-body">
              <h6 class="card-title"><strong>{{ post.title }}</strong></h6>
              <p class="card-text">Precio: ${{ post.originalPrice }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>

{% include 'footer.html' %} {% endblock %}

futuretech/posts/templates/modifyPost.html
{% extends "base.html" %} {% block content %} {% load static %} {% include 'navbar.html' %}
<title>Modify post</title>
<div class="container mt-4">
  <h2>Modify post</h2>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-body">
              <h5 class="card-text">Name of the Post</h5>
              <h4 class="card-title">{{form.title}}</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="">
            <label for="">Condition</label>
            {{form.condition}}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-body">
              <h5 class="card-text">Description</h5>
              <h4 class="card-text">{{ form.description }}</h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="">
            <label for="">Category</label>
            {{ form.categoryId }}
          </div>
          <div class="">
            <label for="">Brand</label>
            {{form.brandId}}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-body">
              <h5 class="card-text">Images</h5>
              <div class="d-flex flex-wrap">
                <img
                  src="https://via.placeholder.com/150"
                  class="img-thumbnail m-2"
                  alt="Image 1"
                />
                <img
                  src="https://via.placeholder.com/150"
                  class="img-thumbnail m-2"
                  alt="Image 2"
                />
                <img
                  src="https://via.placeholder.com/150"
                  class="img-thumbnail m-2"
                  alt="Image 3"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="">
            <label for="">stock</label>
            {{ form.stock }}
          </div>
          <div class="">
            <label for="">Original price</label>
            {{ form.originalPrice }}
          </div>
        </div>
      </div>
      <div>
        <button type="submit" class="btn btn-primary col-md-2">Modify</button>
        <button class="btn btn-danger col-md-2"><a href="{% url 'sellerCentral' %}"></a>Cancel</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

futuretech/posts/templates/navbar.html
{% extends 'base.html'%} {% block content %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Future Tech</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        {% if user.seller %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sellerProfile' %}">
              <img class="perfil-img" src="{% static 'img/favicon.png' %}"></img>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sellerProfile' %}">{{ user.username }}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">
              <img class="perfil-img" src="{% static 'img/favicon.png' %}"></img>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">{{ user.username }}</a>
          </li>
        {% endif %}
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

futuretech/posts/templates/productPage.html
{% extends 'base.html'%}
{% block content %}
{% load static %}
{% include 'navbar.html' %}
<title>FutureTech</title>
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <div
        id="imageCarousel"
        class="carousel slide mt-4"
        data-ride="carousel"
        style="width: 100%"
      >
        <div class="carousel-inner">
          {% for post_image in post.postimage_set.all %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img
                src="{{ post_image.image.url }}"
                class="d-block w-100"
                alt="{{ post.title }}"
              />
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h2 class="mb-3">{{ post.title }}</h2>
      <p class="text-muted">Category: {{ post.getCategoryName }}</p>
      <p class="text-muted">Brand: {{ post.getBrandName }}</p>
      <p>Condition: <span class="text-success">{{ post.condition }}</span></p>
      <p>{{ post.description }}</p>
      <h3 class="text-success font-weight-bold">${{ post.originalPrice }}</h3>
      <div class="form-group">
        <form method="post" action="{% url 'buyNow' post.id %}">
          {% csrf_token %} 
          <label for="quantity">Quantity:</label>
          {{ form.quantity }}
        </div>
        <button class="btn btn-primary btn-lg">Buy now</button>
        {{ form.error }}
        </form>
        <div class="mt-4">
          <h4>Stock: {{ post.stock }}</h4>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'footer.html' %}
{% endblock%}